Make crypt.c condtionally built using automake rather than having the file wrapped in an #ifdef/#endif
git-svn-id: http://svn.ratbox.org/svnroot/ircd-ratbox/trunk@20738 b93f080a-4cfa-0310-a19a-80a68f531ef9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -466,7 +466,7 @@ ac_includes_default="\
 #endif"
 
 ac_subdirs_all="$ac_subdirs_all libltdl"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot LEX CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEXLIB LEX_OUTPUT_ROOT EGREP INCLTDL LIBLTDL MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CPP AS RM CP MV LN SED AR LD RANLIB TOUCH YACC STATIC_MODULES_TRUE STATIC_MODULES_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO ac_ct_AR ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs MINGW_TRUE MINGW_FALSE RESOLVER CRYPT_LIB ALLOCA ENCSPEED ZLIB_LD SERVLINK ETC_DIR confdir LOG_DIR logdir HELP_DIR helpdir MODULE_DIR moduledir SELECT_TYPE ENABLE_SERVICES_TRUE ENABLE_SERVICES_FALSE SSL_SRCS_ENABLE SSL_INCLUDES SSL_LIBS PICFLAGS SEDOBJ IRCD_PREFIX LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot LEX CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE LEXLIB LEX_OUTPUT_ROOT EGREP INCLTDL LIBLTDL MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CPP AS RM CP MV LN SED AR LD RANLIB TOUCH YACC STATIC_MODULES_TRUE STATIC_MODULES_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO ac_ct_AR ac_ct_RANLIB CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL subdirs MINGW_TRUE MINGW_FALSE RESOLVER NEED_CRYPT_TRUE NEED_CRYPT_FALSE CRYPT_LIB ALLOCA ENCSPEED ZLIB_LD SERVLINK ETC_DIR confdir LOG_DIR logdir HELP_DIR helpdir MODULE_DIR moduledir SELECT_TYPE ENABLE_SERVICES_TRUE ENABLE_SERVICES_FALSE SSL_SRCS_ENABLE SSL_INCLUDES SSL_LIBS PICFLAGS SEDOBJ IRCD_PREFIX LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -23007,6 +23007,7 @@ CRYPT_LIB=$ac_cv_search_crypt
 if test "$CRYPT_LIB" = "none required"; then
 	unset CRYPT_LIB
 elif test "$CRYPT_LIB" = no; then
+	need_crypt=yes;
 
 cat >>confdefs.h <<\_ACEOF
 #define NEED_CRYPT 1
@@ -23014,6 +23015,18 @@ _ACEOF
 
 	unset CRYPT_LIB
 fi
+
+
+
+if test x"$need_crypt" == "xyes"; then
+  NEED_CRYPT_TRUE=
+  NEED_CRYPT_FALSE='#'
+else
+  NEED_CRYPT_TRUE='#'
+  NEED_CRYPT_FALSE=
+fi
+
+
 
 
 
@@ -28016,6 +28029,13 @@ echo "$as_me: error: conditional \"MINGW\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${NEED_CRYPT_TRUE}" && test -z "${NEED_CRYPT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"NEED_CRYPT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"NEED_CRYPT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${ENABLE_SERVICES_TRUE}" && test -z "${ENABLE_SERVICES_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_SERVICES\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -28648,6 +28668,8 @@ s,@subdirs@,$subdirs,;t t
 s,@MINGW_TRUE@,$MINGW_TRUE,;t t
 s,@MINGW_FALSE@,$MINGW_FALSE,;t t
 s,@RESOLVER@,$RESOLVER,;t t
+s,@NEED_CRYPT_TRUE@,$NEED_CRYPT_TRUE,;t t
+s,@NEED_CRYPT_FALSE@,$NEED_CRYPT_FALSE,;t t
 s,@CRYPT_LIB@,$CRYPT_LIB,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 s,@ENCSPEED@,$ENCSPEED,;t t
